---
- name: Nginx ve Bağımlılıklarını Kaldır
  hosts: all
  tasks:
      - name: Nginx durdururr
        shell: systemctl stop nginx

      - name: Nginx ve Bağımlılıklarını Kaldır
        apt:
          name: "nginx"
          state: absent
          autoremove: yes
          purge: yes

      - name: nginx-common Paketini Kaldır
        apt:
          name: nginx-common
          state: absent
  
      - name: nginx-core Paketini Kaldır
        apt:
          name: nginx-core
          state: absent

    ## Dosya içerisinde yer alan nginx-common ve ngix-core bağıl işlemler olduğundan onları kaldırmadan nginx kaldırdığınızda  systemctl status nginx komutu sizlere
    ## yanıt olarak nginx servisinin varlığını gösterecektir.

    ## Since nginx-common and ngix-core are relative processes in the file, when you remove nginx without removing them, the systemctl status nginx command will give you
    ## will show the presence of the nginx service in response.